import { getAllImageData } from '../imageList/imageList';
import { displayErrorMessage, updateProgressMessage } from './style';
import { drawShapesViaCoordinates } from '../toolkit/buttonClickEvents/facadeWorkersUtils/drawShapesViaCoordinates/drawShapesViaCoordinates';
import { getCurrentImageId } from '../toolkit/buttonClickEvents/facadeWorkersUtils/stateManager';

let tfModel = null;

function errorHandler() {
  displayErrorMessage();
}

const predictedImageCoordinates = {};

function predict(image) {
  return tfModel.detect(image.data);
}

// TEST
// check that only the images that have been checked have their shapes regenerated

// TEST
// check if it is not too early to display finished as the images still need to
// be updated with shapes

function executeAndRecordPredictionResults(promisesArray, predictionIdToImageId) {
  Promise.all(promisesArray).then((predictions) => {
    for (let i = 0; i < predictions.length; i += 1) {
      predictedImageCoordinates[predictionIdToImageId[i]] = predictions[i];
    }
    drawShapesViaCoordinates(predictedImageCoordinates);
    updateProgressMessage('Finished!');
  });
}

// TEST
// check that the current image shapes are being regenerated by the model

// decided not to store generated shapes because if you have 100 images with
// 100s of shapes, it would lead to significant memory usage
function makePredictionsForAllImages() {
  const predictPromises = [];
  const allImageData = getAllImageData();
  const predictionIdToImageId = [];
  const currentImageId = getCurrentImageId();
  for (let i = 0; i < allImageData.length; i += 1) {
    const image = allImageData[i];
    if (image.numberOfMLGeneratedShapes === 0) {
      predictPromises.push(predict(image));
      predictionIdToImageId.push(i);
    } else if (i === currentImageId) {
      predictPromises.push(predict(image));
      predictionIdToImageId.push(i);
    }
  }
  executeAndRecordPredictionResults(predictPromises, predictionIdToImageId);
}

function loadModel() {
  return new Promise((resolve, reject) => {
    const { cocoSsd } = window;
    cocoSsd.load().then((model) => {
      tfModel = model;
      resolve();
    }).catch(() => {
      reject();
    });
  });
}

function downloadCOCOSSD() {
  return new Promise((resolve, reject) => {
    const cocoSSDScript = document.createElement('script');
    cocoSSDScript.onload = resolve;
    cocoSSDScript.onerror = reject;
    cocoSSDScript.src = 'https://cdn.jsdelivr.net/npm/@tensorflow-models/coco-ssd';
    document.head.appendChild(cocoSSDScript);
  });
}

function downloadTensorflowJS() {
  return new Promise((resolve, reject) => {
    updateProgressMessage('In Progress...');
    const tensorflowJSScript = document.createElement('script');
    tensorflowJSScript.onload = resolve;
    tensorflowJSScript.onerror = reject;
    tensorflowJSScript.src = 'https://cdn.jsdelivr.net/npm/@tensorflow/tfjs';
    document.head.appendChild(tensorflowJSScript);
  });
}

function startMachineLearning() {
  drawShapesViaCoordinates();
  // if (!tfModel) {
  //   downloadTensorflowJS()
  //     .then(() => downloadCOCOSSD())
  //     .then(() => loadModel())
  //     .then(() => makePredictionsForAllImages())
  //     .catch(() => errorHandler());
  // } else {
  //   makePredictionsForAllImages();
  // }
}

export { startMachineLearning as default };
