import { registerHotKeys } from './keyEvents/keyboard/hotKeys';
import registerWindowMouseEvents from './keyEvents/mouse/registerEvents';
import { findUserOS } from './tools/OS/OSManager';
import { constructCanvas } from './canvas/canvas';
import initialiseToolkit from './tools/toolkit/init';
import initialiseLabellerModal from './tools/labellerModal/buttons';
import { initialiseUploadDatasetsModal } from './tools/uploadDatasetsModal/views/viewManager';
import { initialiseMachineLearningModal } from './tools/machineLearningModal/views/viewManager';
import initialiseExportLabelsPopUp from './tools/exportDatasetsPopup/buttonClickEvents';
import initialiseSettingsPopup from './tools/settingsPopup/init';
import assignPassiveEventListeners from './tools/passiveEventListeners/passiveEventListeners';
import initialiseShapeManipulationDeltas from './canvas/objects/deltaValueSetters/initialiseShapeManipulationDeltas';
import initialiseImageListFunctionality from './tools/imageList/init';
import { initialiseCoreButtonPopovers } from './tools/globalStyling/coreButtons/popovers';
import { applyStyling } from './tools/globalStyling/style';
import { initialiseLabelListFunctionality } from './tools/labelList/labelList';
import { initialiseImageSwitchPanelFunctionality } from './tools/imageSwitchPanel/style';

findUserOS();
applyStyling();
constructCanvas();
registerHotKeys();
initialiseToolkit();
initialiseLabellerModal();
initialiseSettingsPopup();
registerWindowMouseEvents();
initialiseCoreButtonPopovers();
initialiseUploadDatasetsModal();
initialiseMachineLearningModal();
initialiseExportLabelsPopUp();
assignPassiveEventListeners();
initialiseImageListFunctionality();
initialiseLabelListFunctionality();
initialiseImageSwitchPanelFunctionality();
initialiseShapeManipulationDeltas();
