import initialiseShapeManipulationDeltas from './canvas/objects/deltaValueSetters/initialiseShapeManipulationDeltas';
import assignPassiveEventListeners from './tools/passiveEventListeners/passiveEventListeners';
import { initialisePulseAnimationCancelling } from './tools/utils/buttons/pulseAnimation';
import { initialiseImageSwitchPanelFunctionality } from './tools/imageSwitchPanel/style';
import { initialiseCoreButtonPopovers } from './tools/globalStyling/buttons/popovers';
import initialiseRemoveImagesModal from './tools/imageList/removeImages/modal/init';
import initialiseBrowserExitHandler from './tools/browserExit/browserExitHandler';
import initialiseDragAndDropFunctionality from './tools/dragAndDrop/dragAndDrop';
import { initialiseWindowDimService } from './tools/dimWindow/dimWindowService';
import initialiseExportDatasetsPopup from './tools/exportDatasetsPopup/init';
import registerWindowMouseEvents from './keyEvents/mouse/registerEvents';
import initialiseImageListFunctionality from './tools/imageList/init';
import initialiseLabelListFunctionality from './tools/labelList/init';
import { initialiseSettingsPopup } from './tools/settingsPopup/init';
import initialiseLabellerModal from './tools/labellerModal/buttons';
import { registerHotKeys } from './keyEvents/keyboard/hotKeys';
import initialiseWelcomeModal from './tools/welcomeModal/init';
import { applyStyling } from './tools/globalStyling/style';
import initialiseToolkit from './tools/toolkit/init';
import { findUserOS } from './tools/OS/OSManager';
import { constructCanvas } from './canvas/canvas';
import initialiseText from './tools/text/init';

findUserOS();
applyStyling();
constructCanvas();
registerHotKeys();
initialiseText();
initialiseToolkit();
initialiseLabellerModal();
initialiseSettingsPopup();
registerWindowMouseEvents();
initialiseWindowDimService();
initialiseCoreButtonPopovers();
initialiseExportDatasetsPopup();
assignPassiveEventListeners();
initialiseRemoveImagesModal();
initialiseImageListFunctionality();
initialiseLabelListFunctionality();
initialiseDragAndDropFunctionality();
initialiseImageSwitchPanelFunctionality();
initialisePulseAnimationCancelling();
initialiseShapeManipulationDeltas();
initialiseBrowserExitHandler();
initialiseWelcomeModal();
